Add downtimes.conf template
adfinis-sygroup/ansible-role-icinga2_master pull request #95
Opened 2021-01-05 14:07 UTC by ayekat

##### SUMMARY

Icinga2 Director does not provide any functionality to set recurring downtimes, so modifying the configuration directly is necessary for this.

This allows setting downtimes for a given set of services on a given set of hosts.

##### ISSUE TYPE

 - Feature Pull Request

##### ANSIBLE VERSION

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/{{user}}/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
```

2021-01-05 14:13 UTC, eyenx requested changes
Also pls add the `icinga2_master_downtimes` variable in the `README.md`

2021-01-05 14:13 UTC, eyenx commented on templates/etc/icinga2/conf.d/downtimes.conf.j2
> +    "{{ downtime.hosts | join('",\n    "') }}"
```suggestion
    "{{ downtime.services | join('",\n    "') }}"
```

2021-01-05 14:14 UTC, eyenx commented on templates/etc/icinga2/conf.d/downtimes.conf.j2
> +    "{{ downtime.hosts | join('",\n    "') }}"
016fbac solved this

2021-01-05 14:14 UTC, ayekat commented on templates/etc/icinga2/conf.d/downtimes.conf.j2
> +    "{{ downtime.hosts | join('",\n    "') }}"
Thanks! Fixed!

2021-01-05 14:29 UTC, merged

2021-01-06 12:31 UTC, michaelimfeld commented
A little too late: I think it would make sense to make this a bit more generic since this only allows to set downtimes on service objects but not on host objects.

2021-01-06 12:58 UTC, eyenx commented
Would you mind opening an issue for this?